### ISSUE TITLE
XCloseDisplay segfault with XNVCtrl when exiting app

### ISSUE THREAD

**Issue by jackun** [flightlessmango/MangoHud#200]
```
#0  0x00007ffff7b961d0 in ?? ()
#1  0x00007ffff777d312 in XCloseDisplay () from /usr/lib/libX11.so.6
#2  0x00007ffff488c06f in operator() (__closure=0x555555b5a350, dpy=0x555555f6ce00) at ../../src/nvctrl.cpp:61
```

```
7ffff7b96000-7ffff7b99000 r-xp 00002000 00:1a 35029863                   /usr/lib/libXNVCtrl.so.0.0.0
```

But only with primus_vk?

**Comment by rtentser** [comment]
May be related: https://aur.archlinux.org/pkgbase/mangohud-git/#comment-749468. Or not.

**Comment by jackun** [comment]
No. Are you getting it with 32bit games? Afaik there's no lib32-xnvctrl.

**Comment by rtentser** [comment]
No, i'm getting it in wine+dxvk with "The Dwarves" which is 64-bit game.

**Comment by flightlessmango** [comment]
re-open if still an issue
