### ISSUE TITLE
MangoHud causes Midair: CE to crash on game launch.

### ISSUE THREAD

**Issue by lwilletts** [flightlessmango/MangoHud#240]
Hi, I posted about this in the #mangohud-dev channel last night, but wanted to make an issue to dump all the relevant info. The game in question is [Midair: CE](https://store.steampowered.com/app/1231210/Midair_Community_Edition/) and is currently in closed beta, but uses Unreal Engine 4.20 to produce a native version of the game using vulkan. I have
[MidairCE.log](https://github.com/flightlessmango/MangoHud/files/4806072/MidairCE.log) available here, and shows mangohud struggling.

I have no issue launching the game up with the standard mesa overlay. If any of you need a key to the game in order to test, I can arrange that with the development team.

**Comment by jackun** [comment]
_Might_ be useful to check if vkBasalt also crashes similarly.

```
(gdb) bt
#0  0x00007ffff21a7355 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff2190853 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff606875d in  ()
    at /home/fyr/.local/share/Steam/steamapps/common/Midair Community Edition/MidairCE/Binaries/Linux/../../../Engine/Binaries/ThirdParty/CEF3/Linux/libcef.so
#3  0x00007ffff6068869 in  ()
    at /home/fyr/.local/share/Steam/steamapps/common/Midair Community Edition/MidairCE/Binaries/Linux/../../../Engine/Binaries/ThirdParty/CEF3/Linux/libcef.so
#4  0x00007ffff60658b3 in std::__terminate(void (*)()) ()
    at /home/fyr/.local/share/Steam/steamapps/common/Midair Community Edition/MidairCE/Binaries/Linux/../../../Engine/Binaries/ThirdParty/CEF3/Linux/libcef.so
#5  0x00007ffff6067056 in  ()
    at /home/fyr/.local/share/Steam/steamapps/common/Midair Community Edition/MidairCE/Binaries/Linux/../../../Engine/Binaries/ThirdParty/CEF3/Linux/libcef.so
#6  0x00007ffff200d3cb in std::__throw_bad_cast() ()
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/exception.h:63
#7  0x00007ffff20b4f1c in std::__check_facet<std::ctype<char> >(std::ctype<char> const*) (__f=0x0)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/locale_facets.h:877
```

**Comment by lwilletts** [comment]
```
Thread 1 "MidairCE-Linux-" received signal SIGABRT, Aborted.
0x00007ffff240d355 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff240d355 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff23f6853 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff62d075d in  ()
    at /home/fyr/.local/share/Steam/steamapps/common/Midair Community Edition/MidairCE/Binaries/Linux/../../../Engine/Binaries/ThirdParty/CEF3/Linux/libcef.so
#3  0x00007ffff62d0869 in  ()
    at /home/fyr/.local/share/Steam/steamapps/common/Midair Community Edition/MidairCE/Binaries/Linux/../../../Engine/Binaries/ThirdParty/CEF3/Linux/libcef.so
#4  0x00007ffff62cd8b3 in std::__terminate(void (*)()) ()
    at /home/fyr/.local/share/Steam/steamapps/common/Midair Community Edition/MidairCE/Binaries/Linux/../../../Engine/Binaries/ThirdParty/CEF3/Linux/libcef.so
#5  0x00007ffff62cf056 in  ()
    at /home/fyr/.local/share/Steam/steamapps/common/Midair Community Edition/MidairCE/Binaries/Linux/../../../Engine/Binaries/ThirdParty/CEF3/Linux/libcef.so
#6  0x00007fffc4af03cb in std::__throw_bad_cast() ()
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/exception.h:63
#7  0x00007fff483a2ef5 in vkBasalt::Logger::emitMsg(vkBasalt::LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
    at /usr/lib/libvkbasalt.so
#8  0x00007fff48374ca3 in vkBasalt::Config::Config() () at /usr/lib/libvkbasalt.so

```

**Comment by flightlessmango** [comment]
Any changes on this?

**Comment by lwilletts** [comment]
I'm afraid to say there has been no change to the behaviour.

**Comment by flightlessmango** [comment]
is this still an issue?
